### ISSUE TITLE
Using grunt

### ISSUE THREAD

**Issue by PabloSajnovsky** [snollygolly/IsoCitySim#2]
# When using grunt, I got this error:

```bash
Running "browserify:build" (browserify) task
>>Error: module "./plugins/Roads" not found from "/home/pablo/IsoCitySim/game/main.js"
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

**Comment by snollygolly** [comment]
I'm so sorry it took me forever to reply.  I didn't see this until just now.

Are you running grunt in the root project folder?  Have you made any changes to the project, or is this a fresh clone?

**Comment by mnzt** [comment]
^ :grinning:
